# Generated by Django 2.0.7 on 2018-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyitem',
            name='relation_in_graph',
        ),
        migrations.AddField(
            model_name='studyitem',
            name='relations_in_graph',
            field=models.ManyToManyField(related_name='_studyitem_relations_in_graph_+', to='server.StudyItem'),
        ),
    ]
