# Generated by Django 2.0.7 on 2018-07-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180722_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyitem',
            name='tags',
        ),
    ]
