# Generated by Django 2.0.7 on 2018-07-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_studyitem_relations_in_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyItemsRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_position', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='server.StudyItem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='server.StudyItem')),
            ],
        ),
        migrations.AddField(
            model_name='studyitem',
            name='relations_in_graph',
            field=models.ManyToManyField(related_name='related_to', through='server.StudyItemsRelation', to='server.StudyItem'),
        ),
    ]
