# Generated by Django 2.0.7 on 2018-07-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20180723_1555'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studyitemsrelation',
            table='StudyItemsRelations',
        ),
    ]
