# Generated by Django 2.0.7 on 2018-07-24 08:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20180723_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_language', models.CharField(max_length=128)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'Description',
            },
        ),
        migrations.AlterField(
            model_name='studyitem',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='description',
            name='study_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.StudyItem'),
        ),
    ]
