# Generated by Django 2.0.7 on 2018-07-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20180724_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyitem',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RenameField(
            model_name='studyitem',
            old_name='study_item_type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='studyitem',
            old_name='minimal_plugin_version',
            new_name='min_plugin_version',
        ),
    ]
