# Generated by Django 2.0.7 on 2018-07-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20180724_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='studyitem',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='studyitem',
            name='edition_date',
        ),
    ]
