# Generated by Django 2.0.7 on 2018-07-25 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20180724_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
