# Generated by Django 2.0.7 on 2018-07-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20180725_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyitem',
            name='version',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
