# Generated by Django 2.0.7 on 2018-07-28 16:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0014_auto_20180728_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_language', models.CharField(max_length=128)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'Description',
            },
        ),
        migrations.CreateModel(
            name='StudyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_plugin_version', models.CharField(max_length=128, null=True)),
                ('version', models.BigIntegerField(default=17201801119)),
                ('item_type', models.CharField(max_length=128)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'StudyItems',
            },
        ),
        migrations.CreateModel(
            name='StudyItemsRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_position', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='server.StudyItem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='server.StudyItem')),
            ],
            options={
                'db_table': 'StudyItemsRelations',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('tag_type', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='studyitem',
            name='relations_in_graph',
            field=models.ManyToManyField(related_name='related_to', through='server.StudyItemsRelation', to='server.StudyItem'),
        ),
        migrations.AddField(
            model_name='description',
            name='study_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.StudyItem'),
        ),
    ]
