# Generated by Django 2.0.7 on 2018-07-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20180728_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='study_item',
        ),
        migrations.RemoveField(
            model_name='studyitem',
            name='relations_in_graph',
        ),
        migrations.RemoveField(
            model_name='studyitemsrelation',
            name='child',
        ),
        migrations.RemoveField(
            model_name='studyitemsrelation',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='StudyItem',
        ),
        migrations.DeleteModel(
            name='StudyItemsRelation',
        ),
    ]
