# Generated by Django 2.0.7 on 2018-07-28 16:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0016_auto_20180728_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_language', models.CharField(default='en', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'Description',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'File',
            },
        ),
        migrations.CreateModel(
            name='HiddenStudyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(default='public', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(max_length=32)),
                ('minimal_plugin_version', models.BigIntegerField(null=True)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.Description')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.File')),
            ],
            options={
                'db_table': 'HiddenStudyItem',
            },
        ),
        migrations.CreateModel(
            name='HiddenStudyItemsRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_position', models.IntegerField(default=0)),
                ('is_new', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='server.HiddenStudyItem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='server.HiddenStudyItem')),
            ],
            options={
                'db_table': 'HiddenStudyItemsRelation',
            },
        ),
        migrations.CreateModel(
            name='RealStudyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(default='public', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(max_length=32)),
                ('minimal_plugin_version', models.BigIntegerField(null=True)),
                ('relations_with_real_study_items', models.ManyToManyField(related_name='_realstudyitem_relations_with_real_study_items_+', to='server.RealStudyItem')),
            ],
            options={
                'db_table': 'RealStudyItem',
            },
        ),
        migrations.AddField(
            model_name='hiddenstudyitem',
            name='relations_with_hidden_study_items',
            field=models.ManyToManyField(through='server.HiddenStudyItemsRelation', to='server.HiddenStudyItem'),
        ),
    ]
