# Generated by Django 2.0.7 on 2018-07-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20180728_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenstudyitem',
            name='real_study_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.RealStudyItem'),
        ),
    ]
