# Generated by Django 2.0.7 on 2018-07-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_hiddenstudyitem_real_study_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realstudyitem',
            name='relations_with_real_study_items',
        ),
    ]
