# Generated by Django 2.0.7 on 2018-07-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_remove_realstudyitem_relations_with_real_study_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='realstudyitem',
            name='relations_with_real_study_items',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.RealStudyItem'),
        ),
    ]
