# Generated by Django 2.0.7 on 2018-07-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_realstudyitem_relations_with_real_study_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realstudyitem',
            old_name='relations_with_real_study_items',
            new_name='parent',
        ),
    ]
