# Generated by Django 2.0.7 on 2018-08-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_auto_20180803_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HiddenStudyItem',
            new_name='ContentStudyItem',
        ),
        migrations.AlterModelTable(
            name='contentstudyitem',
            table='ContentStudyItem',
        ),
        migrations.AlterModelTable(
            name='hiddenstudyitemsrelation',
            table='ContentStudyItemsRelation',
        ),
    ]
