# Generated by Django 2.0.7 on 2018-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_auto_20180803_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HiddenStudyItemsRelation',
            new_name='ContentStudyItemsRelation',
        ),
        migrations.RemoveField(
            model_name='contentstudyitem',
            name='relations_with_hidden_study_items',
        ),
        migrations.AddField(
            model_name='contentstudyitem',
            name='relations_with_content_study_items',
            field=models.ManyToManyField(through='server.ContentStudyItem', to='server.ContentStudyItem'),
        ),
    ]
