# Generated by Django 2.0.7 on 2018-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_auto_20180803_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstudyitem',
            name='minimal_plugin_version',
            field=models.CharField(default='1.7-2018.1-119', max_length=256),
        ),
        migrations.AlterField(
            model_name='infostudyitem',
            name='minimal_plugin_version',
            field=models.CharField(default='1.7-2018.1-119', max_length=256),
        ),
    ]
