# Generated by Django 2.0.7 on 2018-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_auto_20180810_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstudyitem',
            name='relations_with_content_study_items',
            field=models.ManyToManyField(through='server.ContentStudyItemsRelation', to='server.ContentStudyItem'),
        ),
    ]
