# Generated by Django 2.0.7 on 2018-08-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_auto_20180810_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('login', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AlterModelOptions(
            name='contentstudyitemsrelation',
            options={'ordering': ('child_position',)},
        ),
        migrations.AlterField(
            model_name='contentstudyitemsrelation',
            name='child_position',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
