# Generated by Django 2.0.7 on 2018-08-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0030_auto_20180814_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
