# Generated by Django 2.0.7 on 2018-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_user_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstudyitem',
            name='item_type',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='contentstudyitemsrelation',
            name='child_position',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='infostudyitem',
            name='item_type',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
