# Generated by Django 2.0.7 on 2018-08-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0033_auto_20180820_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstudyitemsrelation',
            name='child_position',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
