# Generated by Django 2.0.7 on 2018-08-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0035_auto_20180820_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstudyitem',
            name='relations_with_content_study_items',
            field=models.ManyToManyField(db_index=True, through='server.ContentStudyItemsRelation', to='server.ContentStudyItem'),
        ),
    ]
