# Generated by Django 2.0.7 on 2018-08-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0036_auto_20180820_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstudyitem',
            name='relations_with_content_study_items',
            field=models.ManyToManyField(through='server.ContentStudyItemsRelation', to='server.ContentStudyItem'),
        ),
    ]
