# Generated by Django 2.0.7 on 2018-08-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0037_auto_20180820_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expires_in',
            field=models.PositiveIntegerField(default=3600, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scope',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_type',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
