# Generated by Django 2.0.7 on 2018-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0038_auto_20180827_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
