# Generated by Django 2.0.7 on 2018-08-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_user_access_token_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
