# Generated by Django 2.0.7 on 2018-08-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0040_auto_20180827_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hub_id',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
