# Generated by Django 2.0.7 on 2018-08-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0043_auto_20180828_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstudyitem',
            name='info_study_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.InfoStudyItem'),
        ),
        migrations.AlterField(
            model_name='infostudyitem',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.InfoStudyItem'),
        ),
    ]
