# Generated by Django 2.0.7 on 2018-08-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0044_auto_20180828_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentstudyitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contentstudyitem',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contentstudyitem',
            name='info_study_item',
        ),
        migrations.RemoveField(
            model_name='contentstudyitem',
            name='relations_with_content_study_items',
        ),
        migrations.RemoveField(
            model_name='contentstudyitemsrelation',
            name='child',
        ),
        migrations.RemoveField(
            model_name='contentstudyitemsrelation',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='infostudyitem',
            name='parent',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='ContentStudyItem',
        ),
        migrations.DeleteModel(
            name='ContentStudyItemsRelation',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='InfoStudyItem',
        ),
    ]
