# Generated by Django 2.0.7 on 2018-08-28 16:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0045_auto_20180828_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentStudyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(default='public', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(db_index=True, max_length=32)),
                ('minimal_plugin_version', models.CharField(default='1.7-2018.1-119', max_length=256)),
                ('description', django.contrib.postgres.fields.jsonb.JSONField()),
                ('file', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'ContentStudyItem',
            },
        ),
        migrations.CreateModel(
            name='ContentStudyItemsRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_position', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_new', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='server.ContentStudyItem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='server.ContentStudyItem')),
            ],
            options={
                'db_table': 'ContentStudyItemsRelation',
                'ordering': ('child_position',),
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_language', models.CharField(default='en', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'Description',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'File',
            },
        ),
        migrations.CreateModel(
            name='InfoStudyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(default='public', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(db_index=True, max_length=32)),
                ('minimal_plugin_version', models.CharField(default='1.7-2018.1-119', max_length=256)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.InfoStudyItem')),
            ],
            options={
                'db_table': 'InfoStudyItem',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=128)),
                ('hub_id', models.CharField(db_index=True, default=None, max_length=128)),
                ('status', models.CharField(default='user', max_length=128)),
                ('registration_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('access_token', models.CharField(default=None, max_length=256, null=True)),
                ('access_token_updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token', models.CharField(default=None, max_length=256, null=True)),
                ('token_type', models.CharField(default=None, max_length=32, null=True)),
                ('expires_in', models.PositiveIntegerField(default=3600, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='contentstudyitem',
            name='info_study_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.InfoStudyItem'),
        ),
        migrations.AddField(
            model_name='contentstudyitem',
            name='relations_with_content_study_items',
            field=models.ManyToManyField(through='server.ContentStudyItemsRelation', to='server.ContentStudyItem'),
        ),
    ]
