# Generated by Django 2.0.7 on 2018-08-28 17:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0046_auto_20180828_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstudyitem',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='contentstudyitem',
            name='file',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
